[package]
name = "rust-mutex"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.60"
parking_lot = {version = "0.12.3", features = ["deadlock_detection"] }
tracing-mutex = { version = "0.3.0", features = ["backtraces", "parkinglot"] }